In [2]:
!pip install scikit-learn
!pip install stargazer
!pip install imbalanced-learn
!{sys.executable} -m pip install plotly
!pip install altair
!pip install statsmodels


Looking in indexes: https://yzh79c:****@artifactory.gm.com/artifactory/api/pypi/python/simple
Looking in indexes: https://yzh79c:****@artifactory.gm.com/artifactory/api/pypi/python/simple
Looking in indexes: https://yzh79c:****@artifactory.gm.com/artifactory/api/pypi/python/simple
/bin/bash: {sys.executable}: command not found
Looking in indexes: https://yzh79c:****@artifactory.gm.com/artifactory/api/pypi/python/simple
Looking in indexes: https://yzh79c:****@artifactory.gm.com/artifactory/api/pypi/python/simple


In [3]:
#Importing/installing modules

import pandas as pd
import altair as alt
import numpy as np
import statsmodels.api as sm
import imblearn
from scipy.stats import chi2_contingency

from stargazer.stargazer import Stargazer
from IPython.core.display import HTML


In [4]:
from altair import pipe, limit_rows, to_values
t = lambda data: pipe(data, limit_rows(max_rows=20000), to_values)
alt.data_transformers.register('custom', t)
alt.data_transformers.enable('custom')

DataTransformerRegistry.enable('custom')

# Supervised learning piece - Predicting headache occurrence

In [7]:
#Importing dataset for supervised learnig piece on headache occurrence. This is based of Scott's cleaned dataset with a few tweaks
main_df = pd.read_csv("CSV_DATA/DAP_2020_CSLB_v1.1.csv") # , header = [0,1]   My Drive
heal_df = pd.read_csv("CSV_DATA/DAP_2020_HLES_health_condition_v1.1.csv")
ownr_df = pd.read_csv("CSV_DATA/DAP_2020_HLES_dog_owner_v1.1.csv")
cncr_df = pd.read_csv("CSV_DATA/DAP_2020_HLES_cancer_condition_v1.1.csv")
envr_df = pd.read_csv("CSV_DATA/DAP_2020_ENVIRONMENT_v1.1.csv")


/opt/oss/conda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3552: DtypeWarning: Columns (119,121,123,125,127,136,167,195,241,242,243,244,245,246,247,248,256,376,520) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)


In [8]:
print(len(main_df))
main_df.head(20)

20096


dog_id  cslb_active_6mo  cslb_avoid   cslb_date  cslb_defecate_6mo  \
0    68063                2           1  2020-11-07                  3   
1    54147                3           5  2020-11-09                  3   
2    43693                3           1  2020-11-14                  3   
3    31102                3           1  2020-11-05                  3   
4    87218                3           1  2020-11-05                  3   
5    38914                3           1  2020-11-05                  3   
6    73203                3           1  2020-11-14                  3   
7    58831                4           1  2020-11-10                  3   
8    80304                1           1  2020-12-04                  1   
9    51443                3           1  2020-12-01                  3   
10   29702                5           5  2020-11-06                  3   
11   40356                3           1  2020-11-04                  3   
12   39845                3           1  2020-11-04                  3   
13   63876                3           1  2020-11-28                  3   
14   88967                3           1  2020-11-29                  3   
15   81319                3           1  2020-12-28                  4   
16   52623                3           2  2020-11-25                  3   
17   10041                2           1  2020-11-04                  3   
18   70923                4           3  2020-11-15                  4   
19   86399                4           1  2020-11-08                  3   

    cslb_find_food  cslb_food_6mo  \
0                1              3   
1                1              3   
2                1              3   
3                1              3   
4                1              3   
5                1              3   
6                1              3   
7                1              3   
8                1              3   
9                1              3   
10               2              4   
11               2              3   
12               1              3   
13               2              3   
14               1              3   
15               2              3   
16               1              3   
17               2              3   
18               2              4   
19               2              3   

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             cslb_other_changes  \
0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           NaN   
1                                                                                                                                                                                                                                                                                                                                                                

In [9]:
heal_df.head(20)

dog_id  hs_condition hs_condition_cause_other_description  \
0    68063         423.0                                  NaN   
1    68063         426.0                                  NaN   
2    68063         712.0                                  NaN   
3    68063         714.0                                  NaN   
4    68063        1617.0                                  NaN   
5    68063        1817.0                                  NaN   
6    54147        1215.0                                  NaN   
7    54147        1803.0                                  NaN   
8    43693         305.0                                  NaN   
9    43693         307.0                                  NaN   
10   43693        1798.0                                  NaN   
11   43693        1810.0                                  NaN   
12   31102         198.0                                  NaN   
13   31102         203.0                                  NaN   
14   31102         305.0                                  NaN   
15   31102         410.0                                  NaN   
16   31102        1615.0                                  NaN   
17   31102        1801.0                                  NaN   
18   87218         102.0                                  NaN   
19   87218         406.0                                  NaN   

    hs_condition_is_congenital hs_condition_other_description  \
0                        False                            NaN   
1                        False                            NaN   
2                        False                            NaN   
3                        False                            NaN   
4                        False                            NaN   
5                        False                            NaN   
6                        False                            NaN   
7                        False                            NaN   
8                        False                            NaN   
9                        False                            NaN   
10                       False   Fungus--toadstools suspected   
11                       False                            NaN   
12                       False              clogged tear duct   
13                       False                            NaN   
14                       False                            NaN   
15                       False                            NaN   
16                       False                            NaN   
17                       False                            NaN   
18                       False                            NaN   
19                       False                            NaN   

    hs_condition_type  hs_diagnosis_month  hs_diagnosis_year  \
0                   4                 3.0             2016.0   
1                   4                 3.0             2016.0   
2                   7                 3.0             2016.0   
3                   7                 8.0             2016.0   
4                  16                 2.0             2017.0   
5                  18                 8.0             2019.0   
6                  12                 3.0             2020.0   
7                  18                 6.0             2018.0   
8                   3                 3.0             2018.0   
9                   3                 1.0             2020.0   
10                 17                 5.0             2011.0   
11                 18                 7.0             2020.0   
12                  1                 8.0             2016.0   
13                  2                 8.0             2016.0   
14                  3                 9.0             2016.0   
15                  4                 7.0             2018.0   
16                 16                 6.0             2018.0   
17                 18                 6.0             2016.0   
18                  1                 1.0             20

In [10]:
ownr_df.head(20)

owner_id  oc_household_adult_count  oc_household_child_count  \
0          1                         2                         0   
1          2                         2                         0   
2          3                         2                         0   
3          4                         2                         0   
4          5                         2                         1   
5          6                         2                         0   
6          7                         2                         0   
7          8                         2                         0   
8          9                         2                         0   
9         10                         1                         0   
10        11                         2                         0   
11        12                         2                         0   
12        13                         2                         0   
13        14                         2                         0   
14        15                         2                         0   
15        16                         2                         0   
16        17                         1                         0   
17        18                         3                         0   
18        19                         1                         0   
19        20                         2                         0   

    oc_household_person_count  oc_primary_residence_census_division  \
0                           2                                   9.0   
1                           2                                   9.0   
2                           2                                   9.0   
3                           2                                   5.0   
4                           3                                   7.0   
5                           2                                   5.0   
6                           2                                   9.0   
7                           2                                   8.0   
8                           2                                   4.0   
9                           1                                   3.0   
10                          2                                   9.0   
11                          2                                   8.0   
12                          2                                   9.0   
13                          2                                   8.0   
14                          2                                   9.0   
15                          2                                   9.0   
16                          1                                   2.0   
17                          3                                   8.0   
18                          1                                   1.0   
19                          2                                   8.0   

    oc_primary_residence_ownership  \
0                                2   
1                                2   
2                                2   
3                                2   
4                                2   
5                                2   
6                                2   
7                                2   
8                                2   
9                                2   
10                               2   
11                               2   
12                               2   
13                               2   
14                               1   
15                               2   
16                               2   
17                               1   
18                               1   
19                               2   

   oc_primary_residence_ownership_other_description  \
0                                               NaN   
1                                               NaN   
2                                               NaN   
3                                               NaN   
4        

In [11]:
cncr_df.head(20)

dog_id  hs_cancer_locations_adrenal_gland  hs_cancer_locations_anal_sac  \
0    29702                              False                         False   
1    86399                              False                         False   
2    92031                              False                         False   
3    39653                              False                         False   
4     2114                              False                         False   
5    64276                              False                         False   
6    43961                              False                         False   
7    60796                              False                         False   
8    90315                              False                         False   
9    46085                              False                         False   
10   40729                              False                         False   
11   15361                              False                         False   
12   79355                              False                         False   
13   35247                              False                         False   
14   42525                              False                         False   
15   19712                              False                         False   
16   69045                              False                         False   
17   88506                              False                         False   
18   44146                              False                         False   
19    4183                              False                         False   

    hs_cancer_locations_bladder_or_urethra  hs_cancer_locations_blood  \
0                                    False                      False   
1                                    False                      False   
2                                    False                      False   
3                                    False                      False   
4                                    False                      False   
5                                    False                      False   
6                                    False                      False   
7                                    False                      False   
8                                    False                      False   
9                                    False                      False   
10                                   False                      False   
11                                   False                      False   
12                                   False                      False   
13                                   False                      False   
14                                   False                      False   
15                                   False                      False   
16                                   False                      False   
17                                   False                      False   
18                                   False                      False   
19                                   False                      False   

    hs_cancer_locations_bone_or_joint  hs_cancer_locations_brain  \
0                               False                      False   
1                               False                      False   
2                               False                      False   
3                               False                      False   
4                               False                      False   
5                               False                      False   
6                               False                      False   
7                               False                      False   
8                                True                      False   
9                               False                      False   
10                              False                      Fal

In [12]:
envr_df.head(20)

dog_id  address_1_or_2  address_month  address_year  cv_area_sqmi  \
0    78858               1             10          2020     18.531685   
1     8332               1              3          2020      1.354809   
2    20441               1             10          2020      9.830563   
3    48533               1              3          2020     24.837548   
4    59287               1             12          2020     21.497858   
5    78852               2             11          2020     38.390288   
6     6672               1              8          2020      1.100332   
7     8197               1             12          2020      0.984622   
8    71271               1              8          2020      7.204690   
9    74844               1              9          2020      6.158658   
10   46610               1             10          2020      0.751605   
11   27679               1             10          2020      0.545898   
12   61817               2             12          2020      5.026792   
13   32395               1             10          2020     28.819012   
14   71627               1             12          2020      0.892922   
15    9832               1             10          2020      0.484023   
16   11452               1             10          2020     19.657348   
17   80995               1             10          2020    225.708714   
18   62136               2             12          2020   1167.336007   
19   84813               1             11          2020      9.966279   

    cv_data_year  cv_disadvantage_index  cv_gini_index  cv_median_income  \
0            1.0                   0.30         0.4040           50743.0   
1            1.0                   0.74         0.4575           27563.0   
2            1.0                   0.12         0.4202           46148.0   
3            1.0                  -1.38         0.5071          131776.0   
4            2.0                  -0.30         0.4719           66491.0   
5            1.0                  -0.76         0.4240           86705.0   
6            1.0                  -0.76         0.2920           92629.0   
7            2.0                  -0.23         0.4850           64130.0   
8            1.0                  -0.68         0.3314           92206.0   
9            1.0                   0.62         0.4966           38466.0   
10           1.0                  -0.81         0.3482           93884.0   
11           1.0                  -1.40         0.3267          113977.0   
12           2.0                  -0.19         0.4755           80438.0   
13           1.0                  -0.38         0.3692           76250.0   
14           2.0                   0.60         0.6113           29416.0   
15           1.0                  -0.57         0.3537           68773.0   
16           1.0                  -0.94         0.4211          111667.0   
17           1.0                  -0.16         0.4681           54738.0   
18           2.0                  -0.05         0.4128           50291.0   
19           1.0                  -0.60         0.3533           85088.0   

    cv_pct_below_125povline  ...  tp_tmpc_norm_09  tp_tmpc_norm_10  \
0                     18.98  ...             71.4             61.3   
1                     36.77  ...             70.3             59.0   
2                     21.93  ...             69.7             57.5   
3                      5.99  ...             61.5             49.2   
4                     23.64  ...             64.9             53.9   
5                      4.92  ...             78.6             72.1   
6                      3.14  ...             56.1             47.2   
7                     13.19  ...             61.5             49.2   
8                      3.29  ...             72.4             62.5   
9                     35.82  ...             79.8             73.8   
10                     7.60  ...             57.5             46.8   
11                     2.90  ... 

In [13]:
# Merging into mega table
print(len(main_df))

# Merge main table with health
merged_df_1 = pd.merge(main_df, heal_df, on="dog_id")
print(len(merged_df_1))

# print(list(merged_df_1.columns))

# merge with cancer table
merged_df_2 = pd.merge(merged_df_1, cncr_df, on="dog_id")
print(len(merged_df_2))

# print(list(merged_df_2.columns))
merged_df_2.head(20)

# merge with environment table
merged_df_3 = pd.merge(merged_df_2, envr_df, on="dog_id")
# print(len(merged_df_3))

# merge with owner table
merged_df_fin = pd.merge(merged_df_3, ownr_df, on="dog_id")
# print(len(merged_df_fin))

# merged_df_fin.head(20)

20096
56747
5721


In [14]:
pd.set_option('display.max_columns', None)

print(merged_df_fin['oc_primary_residence_state'])

0        WA
1        WA
2        WA
3        WA
4        WA
         ..
12093    MN
12094    MN
12095    MN
12096    MN
12097    MN
Name: oc_primary_residence_state, Length: 12098, dtype: object


# Exploratory Data Analysis: Geographic Location

In [15]:
state_neutered_df = merged_df_fin[['oc_primary_residence_state', 'dd_spayed_or_neutered']]
state_neutered_df['dd_spayed_or_neutered_encoded'] = np.where(state_neutered_df['dd_spayed_or_neutered'] == True, 1, 0)
state_neutered_df = state_neutered_df[['oc_primary_residence_state', 'dd_spayed_or_neutered_encoded']]
state_neutered_df = state_neutered_df.groupby(['oc_primary_residence_state']).sum()
state_neutered_df = state_neutered_df.reset_index()


/opt/oss/conda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [16]:
source = state_neutered_df

alt.Chart(source).mark_bar().encode(
    x=alt.X('oc_primary_residence_state', title = 'State'),
    y=alt.Y('dd_spayed_or_neutered_encoded', title = 'Number of neutered respondents per state')
)

/opt/oss/conda3/lib/python3.7/site-packages/altair/utils/data.py:229: AltairDeprecationWarning: alt.pipe() is deprecated, and will be removed in a future release. Use toolz.curried.pipe() instead.
  AltairDeprecationWarning,


alt.Chart(...)

When considering the bar graph above, which displays the amount of survey respondents that reported having neutered their dogs, the fact that most repondents hail from Washington state is in line with our thinking, since the Dog Aging Project is facilitated by the University of Washington. It makes intuitive sense that most of the respondents reside within the study's home state. Another noteworthy observation is the notable presence of Californian respondents, which may not be easily explained away by the state's large population, since other highly populated states like Texas and Florida have a respondent presence several magnitudes lower. If nothing else, the fact that our dataset is highly skewed in favor of the west coast will help us make more informed geographic assertions about our analyses. 

# Exploratory Data Analysis: Gender Distribution

In [17]:
sex_df = merged_df_fin[['oc_primary_residence_state', 'dd_sex']]
sex_df['dd_male'] = np.where(sex_df['dd_sex'] == 1, 1, 0)
sex_df['dd_female'] = np.where(sex_df['dd_sex'] == 2, 1, 0)
sex_df['total'] = 1
sex_df = sex_df.groupby(['oc_primary_residence_state']).sum()
sex_df = sex_df.reset_index()
source = sex_df



percentage_male = alt.Chart(source).transform_joinaggregate(
    TotalRespondents='sum(total)',
).transform_calculate(
    PercentOfTotal="datum.dd_male / datum.TotalRespondents"
).mark_bar().encode(
    alt.X('PercentOfTotal:Q', axis=alt.Axis(format='.0%'), title = 'Percentage of male dogs by state'),
    y='oc_primary_residence_state:N'
)


percentage_female = alt.Chart(source).transform_joinaggregate(
    TotalRespondents='sum(total)',
).transform_calculate(
    PercentOfTotal="datum.dd_female / datum.TotalRespondents"
).mark_bar().encode(
    alt.X('PercentOfTotal:Q', axis=alt.Axis(format='.0%'), title = 'Percentage of female dogs by state'),
    y='oc_primary_residence_state:N'
)

percentage_male | percentage_female



/opt/oss/conda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  
/opt/oss/conda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/opt/oss/conda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] 

alt.HConcatChart(...)

The visualization above depicts the percentage of respondents by state, aggregated by gender. The primary purpose of constructing this graph was to ascertain whether or not there was any salient gender imbalances within our population, but in doing so, we have uncovered an entirely seperate issue, in the sense that none of the percentage totals for any given state add up to 100%. This indicates a general prevalence of non-responses for this particularly important field, which may imply the number of records we can truly utilize to train our predictive models is smaller than we intially anticipated, should we decide to use this field as a predictor.

# Exploratory Data Analysis: Age Distribution

In [18]:
age_df = merged_df_fin[['oc_primary_residence_state', 'dd_age_years']]

source = age_df

alt.Chart(source).mark_bar().encode(
    alt.X("dd_age_years:Q", bin=True),
    y='count()',
)

alt.Chart(...)

The above age distribution of dogs included in the study is intriguing, in the sense that it's visibly skewed to the right, towards more advanced dog ages. Current consensus agrees that large dog breeds are considered senior as early as ages 6-7. medium dog breeds at ages 8-9, and smaller dog breeds at 10-12. The brunt of respondents appear to fall between ages 8 and 16, suggesting that much of our population could be considered of senior age. This observation would be important to keep in mind should we discover a diseases highly correlated with age, such as cancer, osteoarthritis, and canine dementia. (https://be.chewy.com/senior-dog-age-at-what-age-is-my-dog-considered-a-senior/)

In [19]:
##LOOKING AT NEUTERED VS UNNEUTERED AND AGGRESSION (+ OTHER BEHAVIORAL FACTORS)

# Exploratory Data Analysis: Spayed/Neutered Distribution

In [82]:
spayed_neutered = merged_df_fin[['oc_primary_residence_state', 'dd_spayed_or_neutered']]
spayed_neutered['Neutered'] = np.where(spayed_neutered['dd_spayed_or_neutered'] == True, 1, 0)
spayed_neutered['Not_Neutered'] = np.where(spayed_neutered['dd_spayed_or_neutered'] == False, 1, 0)
spayed_neutered['total'] = 1
spayed_neutered = spayed_neutered.groupby(['oc_primary_residence_state']).sum()
spayed_neutered = spayed_neutered.reset_index()
source = spayed_neutered



percentage_spayed = alt.Chart(source).transform_joinaggregate(
    TotalRespondents='sum(total)',
).transform_calculate(
    PercentOfTotal="datum.Neutered / datum.TotalRespondents"
).mark_bar().encode(
    alt.X('PercentOfTotal:Q', axis=alt.Axis(format='.0%'), title = 'Percentage spayed/neutered by state'),
    y='oc_primary_residence_state:N'
)


percentage_unspayed = alt.Chart(source).transform_joinaggregate(
    TotalRespondents='sum(total)',
).transform_calculate(
    PercentOfTotal="datum.Not_Neutered / datum.TotalRespondents"
).mark_bar().encode(
    alt.X('PercentOfTotal:Q', axis=alt.Axis(format='.0%'), title = 'Percentage unspayed/unneutered by state'),
    y='oc_primary_residence_state:N'
)


percentage_spayed | percentage_unspayed



/opt/oss/conda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  
/opt/oss/conda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/opt/oss/conda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] 

alt.HConcatChart(...)

The concatenated bar charts above display the percentage of spayed and neutered/unspayed and unneutered dogs by state. It's immediately apparant that, for several states, none of the respondents(that had a non-null response to the question) reported that their dog was not spayed/neutered. This confirms our preconceived notion that the majority of respondents have voluntarily spayed/neutered their dogs.

# Quantitative Analysis: Neutering/Spaying vs. Social Behaviors

In [21]:
aggression_df = merged_df_fin[['dd_spayed_or_neutered', 'db_aggression_level_approached_while_eating', 'db_aggression_level_delivery_workers_at_home',
                               'db_aggression_level_food_taken_away', 'db_aggression_level_on_leash_unknown_dog', 'db_aggression_level_on_leash_unknown_human',
                              'db_aggression_level_toys_taken_away', 'db_aggression_level_unknown_aggressive_dog', 'db_aggression_level_unknown_human_near_yard']]

fear_anxiety_df = merged_df_fin[['dd_spayed_or_neutered', 'db_fear_level_bathed_at_home', 'db_fear_level_loud_noises',
                                'db_fear_level_nails_clipped_at_home', 'db_fear_level_unknown_aggressive_dog', 'db_fear_level_unknown_dogs',
                                'db_fear_level_unknown_human_away_from_home', 'db_fear_level_unknown_human_touch', 'db_fear_level_unknown_objects_outside',
                                'db_fear_level_unknown_situations']]

excitability_df = merged_df_fin[['dd_spayed_or_neutered', 'db_excitement_level_before_car_ride', 'db_excitement_level_before_walk']]

separation_df = merged_df_fin[['dd_spayed_or_neutered', 'db_left_alone_barking_frequency', 'db_left_alone_restlessness_frequency', 'db_left_alone_scratching_frequency']]

attachment_df = merged_df_fin[['dd_spayed_or_neutered', 'db_attention_seeking_follows_humans_frequency', 'db_attention_seeking_sits_close_to_humans_frequency']]

training_df = merged_df_fin[['dd_spayed_or_neutered',  'db_training_distraction_frequency','db_training_obeys_sit_command_frequency',
                            'db_training_obeys_stay_command_frequency']]


miscellaneous_df = merged_df_fin[['dd_spayed_or_neutered', 'db_barks_frequency', 'db_chases_birds_frequency', 'db_chases_squirrels_frequency',
                    'db_chases_tail_frequency', 'db_chews_inappropriate_objects_frequency', 'db_defecates_alone_frequency',
                    'db_energetic_frequency', 'db_escapes_home_or_property_frequency', 'db_hyperactive_frequency',
                    'db_playful_frequency', 'db_pulls_leash_frequency', 'db_urinates_alone_frequency', 'db_urinates_in_home_frequency']]



# CHI SQUARE TESTS

### Aggression

In [22]:
# p = pd.Series()
# for feature in [c for c in aggression_df.columns if c != 'dd_spayed_or_neutered']:
#    _,p[feature],_,_ = chi2_contingency(aggression_df.pivot_table('dd_spayed_or_neutered',feature))


crosstab_db_aggression_level_approached_while_eating = pd.crosstab(aggression_df.dd_spayed_or_neutered, aggression_df.db_aggression_level_approached_while_eating)
crosstab_db_aggression_level_delivery_workers_at_home = pd.crosstab(aggression_df.dd_spayed_or_neutered, aggression_df.db_aggression_level_delivery_workers_at_home)
crosstab_db_aggression_level_food_taken_away = pd.crosstab(aggression_df.dd_spayed_or_neutered, aggression_df.db_aggression_level_food_taken_away)
crosstab_db_aggression_level_on_leash_unknown_dog = pd.crosstab(aggression_df.dd_spayed_or_neutered, aggression_df.db_aggression_level_on_leash_unknown_dog)
crosstab_db_aggression_level_on_leash_unknown_human = pd.crosstab(aggression_df.dd_spayed_or_neutered, aggression_df.db_aggression_level_on_leash_unknown_human)
crosstab_db_aggression_level_toys_taken_away = pd.crosstab(aggression_df.dd_spayed_or_neutered, aggression_df.db_aggression_level_toys_taken_away)
crosstab_db_aggression_level_unknown_aggressive_dog = pd.crosstab(aggression_df.dd_spayed_or_neutered, aggression_df.db_aggression_level_unknown_aggressive_dog)
crosstab_db_aggression_level_unknown_human_near_yard = pd.crosstab(aggression_df.dd_spayed_or_neutered, aggression_df.db_aggression_level_unknown_human_near_yard)

contingency_tables = [crosstab_db_aggression_level_approached_while_eating, crosstab_db_aggression_level_delivery_workers_at_home ,
                     crosstab_db_aggression_level_food_taken_away, crosstab_db_aggression_level_on_leash_unknown_dog,
                     crosstab_db_aggression_level_on_leash_unknown_human, crosstab_db_aggression_level_toys_taken_away,
                     crosstab_db_aggression_level_unknown_aggressive_dog, crosstab_db_aggression_level_unknown_human_near_yard ]


p_list = []

for table in contingency_tables:
    c, p, dof, expected = chi2_contingency(table)  
    p_list.append(p)

p_list

# crosstab_db_aggression_level_approached_while_eating_normalize = pd.crosstab(aggression_df.dd_spayed_or_neutered, aggression_df.db_aggression_level_approached_while_eating, normalize='index')

# print(crosstab_db_aggression_level_approached_while_eating_normalize)

[1.5376516975528649e-43,
 1.2604078620939303e-10,
 3.354339558600726e-25,
 2.91001507584792e-18,
 2.5287164853333072e-05,
 1.859063323626988e-12,
 3.759155270566461e-50,
 3.3669645930953866e-23]

### FEAR AND ANXIETY

In [23]:
crosstab_db_fear_level_bathed_at_home = pd.crosstab(fear_anxiety_df.dd_spayed_or_neutered, fear_anxiety_df.db_fear_level_bathed_at_home)
crosstab_db_fear_level_loud_noises = pd.crosstab(fear_anxiety_df.dd_spayed_or_neutered, fear_anxiety_df.db_fear_level_loud_noises)
crosstab_db_fear_level_nails_clipped_at_home = pd.crosstab(fear_anxiety_df.dd_spayed_or_neutered, fear_anxiety_df.db_fear_level_nails_clipped_at_home)
crosstab_db_fear_level_unknown_aggressive_dog = pd.crosstab(fear_anxiety_df.dd_spayed_or_neutered, fear_anxiety_df.db_fear_level_unknown_aggressive_dog)
crosstab_db_fear_level_unknown_dogs = pd.crosstab(fear_anxiety_df.dd_spayed_or_neutered, fear_anxiety_df.db_fear_level_unknown_dogs)
crosstab_db_fear_level_unknown_human_away_from_home = pd.crosstab(fear_anxiety_df.dd_spayed_or_neutered, fear_anxiety_df.db_fear_level_unknown_human_away_from_home)
crosstab_db_fear_level_unknown_human_touch = pd.crosstab(fear_anxiety_df.dd_spayed_or_neutered, fear_anxiety_df.db_fear_level_unknown_human_touch)
crosstab_db_fear_level_unknown_objects_outside = pd.crosstab(fear_anxiety_df.dd_spayed_or_neutered, fear_anxiety_df.db_fear_level_unknown_objects_outside)
crosstab_db_fear_level_unknown_situations = pd.crosstab(fear_anxiety_df.dd_spayed_or_neutered, fear_anxiety_df.db_fear_level_unknown_situations)

contingency_tables = [crosstab_db_fear_level_bathed_at_home, crosstab_db_fear_level_loud_noises, crosstab_db_fear_level_nails_clipped_at_home,
                    crosstab_db_fear_level_unknown_aggressive_dog, crosstab_db_fear_level_unknown_dogs, crosstab_db_fear_level_unknown_human_away_from_home,
                    crosstab_db_fear_level_unknown_human_touch, crosstab_db_fear_level_unknown_objects_outside, crosstab_db_fear_level_unknown_situations]


p_list = []

for table in contingency_tables:
    c, p, dof, expected = chi2_contingency(table)  
    p_list.append(p)

p_list




[2.632961109140053e-16,
 5.6854645032164216e-24,
 1.3303487968998245e-20,
 4.269287628536523e-20,
 4.744588891817972e-28,
 2.5105058281299322e-11,
 8.261832480590039e-13,
 0.2926604427096294,
 1.0253972898440499e-26]

### EXCITABILITY

In [24]:
crosstab_db_excitement_level_before_car_ride = pd.crosstab(excitability_df.dd_spayed_or_neutered,excitability_df.db_excitement_level_before_car_ride)
crosstab_db_excitement_level_before_walk = pd.crosstab(excitability_df.dd_spayed_or_neutered,excitability_df.db_excitement_level_before_walk)


contingency_tables = [crosstab_db_excitement_level_before_car_ride, crosstab_db_excitement_level_before_walk ]


p_list = []

for table in contingency_tables:
    c, p, dof, expected = chi2_contingency(table)  
    p_list.append(p)

p_list


[3.265423346312614e-24, 1.1006686047155687e-16]

### Separation

In [25]:
crosstab_db_left_alone_barking_frequency = pd.crosstab(separation_df.dd_spayed_or_neutered, separation_df.db_left_alone_barking_frequency)
crosstab_db_left_alone_restlessness_frequency = pd.crosstab(separation_df.dd_spayed_or_neutered, separation_df.db_left_alone_restlessness_frequency)
crosstab_db_left_alone_scratching_frequency = pd.crosstab(separation_df.dd_spayed_or_neutered, separation_df.db_left_alone_scratching_frequency)

contingency_tables = [crosstab_db_left_alone_barking_frequency, crosstab_db_left_alone_restlessness_frequency, crosstab_db_left_alone_scratching_frequency]



p_list = []

for table in contingency_tables:
    c, p, dof, expected = chi2_contingency(table)  
    p_list.append(p)

p_list


[6.809987486458215e-11, 1.5711402190590372e-19, 2.6495736511713206e-13]

### Attachment

In [26]:
crosstab_db_attention_seeking_follows_humans_frequency = pd.crosstab(attachment_df.dd_spayed_or_neutered, attachment_df.db_attention_seeking_follows_humans_frequency)
crosstab_db_attention_seeking_sits_close_to_humans_frequency = pd.crosstab(attachment_df.dd_spayed_or_neutered, attachment_df.db_attention_seeking_sits_close_to_humans_frequency)

contingency_tables = [crosstab_db_attention_seeking_follows_humans_frequency, crosstab_db_attention_seeking_sits_close_to_humans_frequency]


p_list = []

for table in contingency_tables:
    c, p, dof, expected = chi2_contingency(table)  
    p_list.append(p)

p_list

[3.849854364297653e-05, 0.00014311678388290278]

### Training Difficulty

In [27]:
crosstab_db_training_distraction_frequency = pd.crosstab(training_df.dd_spayed_or_neutered, training_df.db_training_distraction_frequency)
crosstab_db_training_obeys_sit_command_frequency = pd.crosstab(training_df.dd_spayed_or_neutered, training_df.db_training_obeys_sit_command_frequency)
crosstab_db_training_obeys_stay_command_frequency = pd.crosstab(training_df.dd_spayed_or_neutered, training_df.db_training_obeys_stay_command_frequency)

contingency_tables = [crosstab_db_training_distraction_frequency, crosstab_db_training_obeys_sit_command_frequency, crosstab_db_training_obeys_stay_command_frequency]



p_list = []

for table in contingency_tables:
    c, p, dof, expected = chi2_contingency(table)  
    p_list.append(p)

p_list



[2.949072473309456e-17, 3.3626038153039484e-17, 3.8913035462851366e-15]

### MISCELLANEOUS BEHAVIORS

In [28]:
crosstab_db_barks_frequency = pd.crosstab(miscellaneous_df.dd_spayed_or_neutered, miscellaneous_df.db_barks_frequency)
crosstab_db_chases_birds_frequency = pd.crosstab(miscellaneous_df.dd_spayed_or_neutered, miscellaneous_df.db_chases_birds_frequency)
crosstab_db_chases_squirrels_frequency = pd.crosstab(miscellaneous_df.dd_spayed_or_neutered, miscellaneous_df.db_chases_squirrels_frequency)
crosstab_db_chases_tail_frequency = pd.crosstab(miscellaneous_df.dd_spayed_or_neutered, miscellaneous_df.db_chases_tail_frequency)
crosstab_db_chews_inappropriate_objects_frequency = pd.crosstab(miscellaneous_df.dd_spayed_or_neutered, miscellaneous_df.db_chews_inappropriate_objects_frequency)
crosstab_db_defecates_alone_frequency = pd.crosstab(miscellaneous_df.dd_spayed_or_neutered, miscellaneous_df.db_defecates_alone_frequency)
crosstab_db_energetic_frequency = pd.crosstab(miscellaneous_df.dd_spayed_or_neutered, miscellaneous_df.db_energetic_frequency)
crosstab_db_escapes_home_or_property_frequency = pd.crosstab(miscellaneous_df.dd_spayed_or_neutered, miscellaneous_df.db_escapes_home_or_property_frequency)
crosstab_db_hyperactive_frequency = pd.crosstab(miscellaneous_df.dd_spayed_or_neutered, miscellaneous_df.db_hyperactive_frequency)
crosstab_db_playful_frequency = pd.crosstab(miscellaneous_df.dd_spayed_or_neutered, miscellaneous_df.db_playful_frequency)
crosstab_db_pulls_leash_frequency = pd.crosstab(miscellaneous_df.dd_spayed_or_neutered, miscellaneous_df.db_pulls_leash_frequency)
crosstab_db_urinates_alone_frequency = pd.crosstab(miscellaneous_df.dd_spayed_or_neutered, miscellaneous_df.db_urinates_alone_frequency)
crosstab_db_urinates_in_home_frequency = pd.crosstab(miscellaneous_df.dd_spayed_or_neutered, miscellaneous_df.db_urinates_in_home_frequency)

contingency_tables = [crosstab_db_barks_frequency, crosstab_db_chases_birds_frequency, crosstab_db_chases_squirrels_frequency,
                     crosstab_db_chases_tail_frequency, crosstab_db_chews_inappropriate_objects_frequency, crosstab_db_defecates_alone_frequency,
                    crosstab_db_energetic_frequency, crosstab_db_escapes_home_or_property_frequency, crosstab_db_hyperactive_frequency,
                    crosstab_db_playful_frequency, crosstab_db_pulls_leash_frequency, crosstab_db_urinates_alone_frequency, crosstab_db_urinates_in_home_frequency]


p_list = []

for table in contingency_tables:
    c, p, dof, expected = chi2_contingency(table)  
    p_list.append(p)

p_list

[2.0067617412595145e-23,
 0.0036775432002599793,
 5.203276286242527e-08,
 0.03281640696501434,
 1.8428326223209786e-06,
 3.899206375428685e-39,
 7.627356660916509e-13,
 2.815950411167686e-18,
 2.43464504909615e-09,
 3.2610514728541365e-17,
 6.690059393198481e-22,
 1.9721036753757673e-42,
 1.1496710626298889e-42]

On a surface level, with almost no exception, the p-values produced from the above chi squared tests of 'dd_spayed_or_neutered' against various social behavior explanatory variables are very small and significant up to an alpha of 0.01, indicating that the observed data is very unlikely to have been produced by pure chance - in other words, that there is in fact a relationship between the variable 'dd_spayed_or_neutered' and the behavior variables, and that the probability that the data could deviate from the null hypothesis of 'no relationship' in future samples is nearly 100%. I am hesitant to put much stock into this finding, so prior to training my models in the upcoming cells, I will ensure to normalize the data first.

# Model Construction: Logistic Regression(Training and Prediction)

In [29]:
# https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html
# Train test split with confusion matrix
    
    
aggression_df_2 = aggression_df.drop(columns=['dd_spayed_or_neutered'])
fear_anxiety_df_2 = fear_anxiety_df.drop(columns=['dd_spayed_or_neutered'])
excitability_df_2 = excitability_df.drop(columns=['dd_spayed_or_neutered'])
separation_df_2 = separation_df.drop(columns=['dd_spayed_or_neutered'])
attachment_df_2 = attachment_df.drop(columns=['dd_spayed_or_neutered'])
training_df_2 = training_df.drop(columns=['dd_spayed_or_neutered'])
miscellaneous_df_2 = miscellaneous_df.drop(columns=['dd_spayed_or_neutered'])


merged_df_fin = merged_df_fin.fillna(merged_df_fin.mean())



/opt/oss/conda3/lib/python3.7/site-packages/ipykernel_launcher.py:14: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  


In [30]:
#Preprocessing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (confusion_matrix, 
                           accuracy_score)

train, test = train_test_split(merged_df_fin, test_size=0.3)
scaler_train = StandardScaler()
scaler_test = StandardScaler()
num_cols_train = train.columns[train.dtypes.apply(lambda c: np.issubdtype(c, np.number))]
num_cols_test = test.columns[test.dtypes.apply(lambda c: np.issubdtype(c, np.number))]
train[num_cols_train] = scaler_train.fit_transform(train[num_cols_train])
test[num_cols_test] = scaler_test.fit_transform(test[num_cols_test])



/opt/oss/conda3/lib/python3.7/site-packages/sklearn/utils/extmath.py:985: RuntimeWarning: invalid value encountered in true_divide
  updated_mean = (last_sum + new_sum) / updated_sample_count
/opt/oss/conda3/lib/python3.7/site-packages/sklearn/utils/extmath.py:990: RuntimeWarning: invalid value encountered in true_divide
  T = new_sum / new_sample_count
/opt/oss/conda3/lib/python3.7/site-packages/sklearn/utils/extmath.py:1020: RuntimeWarning: invalid value encountered in true_divide
  new_unnormalized_variance -= correction ** 2 / new_sample_count
/opt/oss/conda3/lib/python3.7/site-packages/sklearn/utils/extmath.py:985: RuntimeWarning: invalid value encountered in true_divide
  updated_mean = (last_sum + new_sum) / updated_sample_count
/opt/oss/conda3/lib/python3.7/site-packages/sklearn/utils/extmath.py:990: RuntimeWarning: invalid value encountered in true_divide
  T = new_sum / new_sample_count
/opt/oss/conda3/lib/python3.7/site-packages/sklearn/utils/extmath.py:1020: RuntimeWarning:

### Aggression

In [31]:
log_reg = sm.Logit(endog=train['dd_spayed_or_neutered'], exog=train[aggression_df_2.columns]).fit()

stargazer = Stargazer([log_reg])

HTML(stargazer.render_html())

Optimization terminated successfully.
         Current function value: 0.691804
         Iterations 4


In [32]:
Xtest = test[aggression_df_2.columns]
ytest = test['dd_spayed_or_neutered']

yhat = log_reg.predict(Xtest)
prediction = list(map(round, yhat))

In [33]:
# confusion matrix
cm = confusion_matrix(ytest, prediction) 
print ("Confusion Matrix : \n", cm) 
  
# accuracy score of the model
print('Test accuracy = ', accuracy_score(ytest, prediction))

Confusion Matrix : 
 [[  87   15]
 [1821 1707]]
Test accuracy =  0.49421487603305786


### Fear and Anxiety

In [34]:
log_reg = sm.Logit(endog=train['dd_spayed_or_neutered'], exog=train[fear_anxiety_df_2.columns]).fit()

stargazer = Stargazer([log_reg])

HTML(stargazer.render_html())

Optimization terminated successfully.
         Current function value: 0.692277
         Iterations 3


In [35]:
Xtest = test[fear_anxiety_df_2.columns]
ytest = test['dd_spayed_or_neutered']

yhat = log_reg.predict(Xtest)
prediction = list(map(round, yhat))

In [36]:
# confusion matrix
cm = confusion_matrix(ytest, prediction) 
print ("Confusion Matrix : \n", cm) 
  
# accuracy score of the model
print('Test accuracy = ', accuracy_score(ytest, prediction))

Confusion Matrix : 
 [[  91   11]
 [1904 1624]]
Test accuracy =  0.4724517906336088


### Excitability

In [37]:
log_reg = sm.Logit(endog=train['dd_spayed_or_neutered'], exog=train[excitability_df_2.columns]).fit()

stargazer = Stargazer([log_reg])

HTML(stargazer.render_html())

Optimization terminated successfully.
         Current function value: 0.692943
         Iterations 3


In [38]:
Xtest = test[excitability_df_2.columns]
ytest = test['dd_spayed_or_neutered']

yhat = log_reg.predict(Xtest)
prediction = list(map(round, yhat))

In [39]:
# confusion matrix
cm = confusion_matrix(ytest, prediction) 
print ("Confusion Matrix : \n", cm) 
  
# accuracy score of the model
print('Test accuracy = ', accuracy_score(ytest, prediction))

Confusion Matrix : 
 [[  70   32]
 [2157 1371]]
Test accuracy =  0.396969696969697


### Attachment

In [40]:
log_reg = sm.Logit(endog=train['dd_spayed_or_neutered'], exog=train[attachment_df_2.columns]).fit()

stargazer = Stargazer([log_reg])

HTML(stargazer.render_html())

Optimization terminated successfully.
         Current function value: 0.693035
         Iterations 3


In [41]:
Xtest = test[attachment_df_2.columns]
ytest = test['dd_spayed_or_neutered']

yhat = log_reg.predict(Xtest)
prediction = list(map(round, yhat))

In [42]:
# confusion matrix
cm = confusion_matrix(ytest, prediction) 
print ("Confusion Matrix : \n", cm) 
  
# accuracy score of the model
print('Test accuracy = ', accuracy_score(ytest, prediction))

Confusion Matrix : 
 [[  52   50]
 [1864 1664]]
Test accuracy =  0.4727272727272727


### Training

In [43]:
log_reg = sm.Logit(endog=train['dd_spayed_or_neutered'], exog=train[training_df_2.columns]).fit()

stargazer = Stargazer([log_reg])

HTML(stargazer.render_html())

Optimization terminated successfully.
         Current function value: 0.693057
         Iterations 3


In [44]:
Xtest = test[training_df_2.columns]
ytest = test['dd_spayed_or_neutered']

yhat = log_reg.predict(Xtest)
prediction = list(map(round, yhat))

In [45]:
# confusion matrix
cm = confusion_matrix(ytest, prediction) 
print ("Confusion Matrix : \n", cm) 
  
# accuracy score of the model
print('Test accuracy = ', accuracy_score(ytest, prediction))

Confusion Matrix : 
 [[  56   46]
 [1607 1921]]
Test accuracy =  0.5446280991735537


### Miscellaneous

In [46]:
log_reg = sm.Logit(endog=train['dd_spayed_or_neutered'], exog=train[miscellaneous_df_2.columns]).fit()

stargazer = Stargazer([log_reg])

HTML(stargazer.render_html())

Optimization terminated successfully.
         Current function value: 0.691887
         Iterations 4


In [47]:
Xtest = test[miscellaneous_df_2.columns]
ytest = test['dd_spayed_or_neutered']

yhat = log_reg.predict(Xtest)
prediction = list(map(round, yhat))

In [48]:
# confusion matrix
cm = confusion_matrix(ytest, prediction) 
print ("Confusion Matrix : \n", cm) 
  
# accuracy score of the model
print('Test accuracy = ', accuracy_score(ytest, prediction))

Confusion Matrix : 
 [[  88   14]
 [1570 1958]]
Test accuracy =  0.5636363636363636


# Model Construction: Naive Bayes(Training and Prediction)

### Aggression

In [49]:
from sklearn.naive_bayes import GaussianNB
from sklearn import metrics

aggression_df = aggression_df.dropna()
aggression_df_2 = aggression_df_2.dropna()

X = aggression_df[aggression_df_2.columns]

y = aggression_df['dd_spayed_or_neutered']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

clf = GaussianNB()
y_pred = clf.fit(X_train, y_train).predict(X_test)


print("Number of mislabeled points out of a total %d points : %d" % (X_test.shape[0], (y_test != y_pred).sum()))
print(metrics.classification_report(y_test, y_pred))
print(metrics.confusion_matrix(y_test, y_pred))

Number of mislabeled points out of a total 3458 points : 210
              precision    recall  f1-score   support

       False       0.11      0.16      0.13       102
        True       0.97      0.96      0.97      3356

    accuracy                           0.94      3458
   macro avg       0.54      0.56      0.55      3458
weighted avg       0.95      0.94      0.94      3458

[[  16   86]
 [ 124 3232]]


### Fear and Anxiety

In [50]:
fear_anxiety_df = fear_anxiety_df.dropna()
fear_anxiety_df_2 = fear_anxiety_df_2.dropna()

X = fear_anxiety_df[fear_anxiety_df_2.columns]

y = fear_anxiety_df['dd_spayed_or_neutered']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

clf = GaussianNB()
y_pred = clf.fit(X_train, y_train).predict(X_test)


print("Number of mislabeled points out of a total %d points : %d" % (X_test.shape[0], (y_test != y_pred).sum()))
print(metrics.classification_report(y_test, y_pred))
print(metrics.confusion_matrix(y_test, y_pred))

Number of mislabeled points out of a total 3334 points : 468
              precision    recall  f1-score   support

       False       0.09      0.50      0.16        88
        True       0.98      0.87      0.92      3246

    accuracy                           0.86      3334
   macro avg       0.54      0.68      0.54      3334
weighted avg       0.96      0.86      0.90      3334

[[  44   44]
 [ 424 2822]]


### Excitability

In [51]:
excitability_df = excitability_df.dropna()
excitability_df_2 = excitability_df_2.dropna()

X = excitability_df[excitability_df_2.columns]

y = excitability_df['dd_spayed_or_neutered']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

clf = GaussianNB()
y_pred = clf.fit(X_train, y_train).predict(X_test)


print("Number of mislabeled points out of a total %d points : %d" % (X_test.shape[0], (y_test != y_pred).sum()))
print(metrics.classification_report(y_test, y_pred))
print(metrics.confusion_matrix(y_test, y_pred))

Number of mislabeled points out of a total 3624 points : 99
              precision    recall  f1-score   support

       False       0.00      0.00      0.00        99
        True       0.97      1.00      0.99      3525

    accuracy                           0.97      3624
   macro avg       0.49      0.50      0.49      3624
weighted avg       0.95      0.97      0.96      3624

[[   0   99]
 [   0 3525]]


/opt/oss/conda3/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/oss/conda3/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/oss/conda3/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


### Attachment

In [52]:
attachment_df = attachment_df.dropna()
attachment_df_2 = attachment_df_2.dropna()

X = attachment_df[attachment_df_2.columns]

y = attachment_df['dd_spayed_or_neutered']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

clf = GaussianNB()
y_pred = clf.fit(X_train, y_train).predict(X_test)


print("Number of mislabeled points out of a total %d points : %d" % (X_test.shape[0], (y_test != y_pred).sum()))
print(metrics.classification_report(y_test, y_pred))
print(metrics.confusion_matrix(y_test, y_pred))

Number of mislabeled points out of a total 3625 points : 93
              precision    recall  f1-score   support

       False       0.00      0.00      0.00        93
        True       0.97      1.00      0.99      3532

    accuracy                           0.97      3625
   macro avg       0.49      0.50      0.49      3625
weighted avg       0.95      0.97      0.96      3625

[[   0   93]
 [   0 3532]]


/opt/oss/conda3/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/oss/conda3/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/oss/conda3/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


### Training

In [53]:
training_df = training_df.dropna()
training_df_2 = training_df_2.dropna()

X = training_df[training_df_2.columns]

y = training_df['dd_spayed_or_neutered']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

clf = GaussianNB()
y_pred = clf.fit(X_train, y_train).predict(X_test)


print("Number of mislabeled points out of a total %d points : %d" % (X_test.shape[0], (y_test != y_pred).sum()))
print(metrics.classification_report(y_test, y_pred))
print(metrics.confusion_matrix(y_test, y_pred))

Number of mislabeled points out of a total 3581 points : 102
              precision    recall  f1-score   support

       False       0.00      0.00      0.00       102
        True       0.97      1.00      0.99      3479

    accuracy                           0.97      3581
   macro avg       0.49      0.50      0.49      3581
weighted avg       0.94      0.97      0.96      3581

[[   0  102]
 [   0 3479]]


/opt/oss/conda3/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/oss/conda3/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/oss/conda3/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


### Miscellaneous

In [54]:
miscellaneous_df = miscellaneous_df.dropna()
miscellaneous_df_2 = miscellaneous_df_2.dropna()

X = miscellaneous_df[miscellaneous_df_2.columns]

y = miscellaneous_df['dd_spayed_or_neutered']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

clf = GaussianNB()
y_pred = clf.fit(X_train, y_train).predict(X_test)


print("Number of mislabeled points out of a total %d points : %d" % (X_test.shape[0], (y_test != y_pred).sum()))
print(metrics.classification_report(y_test, y_pred))
print(metrics.confusion_matrix(y_test, y_pred))

Number of mislabeled points out of a total 3459 points : 177
              precision    recall  f1-score   support

       False       0.17      0.16      0.16       108
        True       0.97      0.97      0.97      3351

    accuracy                           0.95      3459
   macro avg       0.57      0.57      0.57      3459
weighted avg       0.95      0.95      0.95      3459

[[  17   91]
 [  86 3265]]


Upon observing the number of mislabeled points generated by the above Gaussian Naive Bayes models, I was initially tempted to laud their performance. However, outputting the classification report paints a different picture. Upon observing the precision scores for each model, it's immediately apparent that the models are exceptionally good at predicting the category 'True' and quite poor at prediciting the category 'False.' The recall scores further suggest that the models were unable to positively identify the category 'False' when presented with it. To me, these findings suggest a significant class imbalance in favor of the category 'True.' In other words, the models only really need to predict the majority class to be performant. To remedy this issue, I will attempt to oversample the minority class.

# Model Construction with Oversampling: Naive Bayes(Training and Prediction)

### Aggression

In [55]:
from imblearn.over_sampling import RandomOverSampler 


In [56]:
X = aggression_df[aggression_df_2.columns]
y = aggression_df['dd_spayed_or_neutered']

oversample = RandomOverSampler(sampling_strategy=0.5, random_state=42)
X_over, y_over = oversample.fit_resample(X, y)
X_train, X_test, y_train, y_test = train_test_split(X_over, y_over, test_size=0.3, random_state=42)

clf = GaussianNB()
y_pred = clf.fit(X_train, y_train).predict(X_test)


print("Number of mislabeled points out of a total %d points : %d" % (X_test.shape[0], (y_test != y_pred).sum()))
print(metrics.classification_report(y_test, y_pred))
print(metrics.confusion_matrix(y_test, y_pred))


Number of mislabeled points out of a total 5034 points : 1407
              precision    recall  f1-score   support

       False       0.66      0.28      0.40      1636
        True       0.73      0.93      0.82      3398

    accuracy                           0.72      5034
   macro avg       0.70      0.61      0.61      5034
weighted avg       0.71      0.72      0.68      5034

[[ 466 1170]
 [ 237 3161]]


### Fear and Anxiety

In [57]:
fear_anxiety_df = fear_anxiety_df.dropna()
fear_anxiety_df_2 = fear_anxiety_df_2.dropna()

X = fear_anxiety_df[fear_anxiety_df_2.columns]

y = fear_anxiety_df['dd_spayed_or_neutered']

oversample = RandomOverSampler(sampling_strategy=0.5, random_state=42)
X_over, y_over = oversample.fit_resample(X, y)
X_train, X_test, y_train, y_test = train_test_split(X_over, y_over, test_size=0.3, random_state=42)


clf = GaussianNB()
y_pred = clf.fit(X_train, y_train).predict(X_test)


print("Number of mislabeled points out of a total %d points : %d" % (X_test.shape[0], (y_test != y_pred).sum()))
print(metrics.classification_report(y_test, y_pred))
print(metrics.confusion_matrix(y_test, y_pred))

Number of mislabeled points out of a total 4858 points : 1680
              precision    recall  f1-score   support

       False       0.49      0.81      0.61      1601
        True       0.86      0.58      0.69      3257

    accuracy                           0.65      4858
   macro avg       0.67      0.69      0.65      4858
weighted avg       0.74      0.65      0.66      4858

[[1296  305]
 [1375 1882]]


### Excitability

In [58]:
excitability_df = excitability_df.dropna()
excitability_df_2 = excitability_df_2.dropna()

X = excitability_df[excitability_df_2.columns]

y = excitability_df['dd_spayed_or_neutered']

oversample = RandomOverSampler(sampling_strategy=0.5, random_state=42)
X_over, y_over = oversample.fit_resample(X, y)
X_train, X_test, y_train, y_test = train_test_split(X_over, y_over, test_size=0.3, random_state=42)

clf = GaussianNB()
y_pred = clf.fit(X_train, y_train).predict(X_test)


print("Number of mislabeled points out of a total %d points : %d" % (X_test.shape[0], (y_test != y_pred).sum()))
print(metrics.classification_report(y_test, y_pred))
print(metrics.confusion_matrix(y_test, y_pred))

Number of mislabeled points out of a total 5282 points : 1627
              precision    recall  f1-score   support

       False       0.57      0.25      0.35      1727
        True       0.71      0.91      0.80      3555

    accuracy                           0.69      5282
   macro avg       0.64      0.58      0.57      5282
weighted avg       0.67      0.69      0.65      5282

[[ 432 1295]
 [ 332 3223]]


### Attachment

In [59]:
attachment_df = attachment_df.dropna()
attachment_df_2 = attachment_df_2.dropna()

X = attachment_df[attachment_df_2.columns]

y = attachment_df['dd_spayed_or_neutered']

oversample = RandomOverSampler(sampling_strategy=0.5, random_state=42)
X_over, y_over = oversample.fit_resample(X, y)
X_train, X_test, y_train, y_test = train_test_split(X_over, y_over, test_size=0.3, random_state=42)

clf = GaussianNB()
y_pred = clf.fit(X_train, y_train).predict(X_test)


print("Number of mislabeled points out of a total %d points : %d" % (X_test.shape[0], (y_test != y_pred).sum()))
print(metrics.classification_report(y_test, y_pred))
print(metrics.confusion_matrix(y_test, y_pred))

Number of mislabeled points out of a total 5284 points : 1714
              precision    recall  f1-score   support

       False       0.00      0.00      0.00      1714
        True       0.68      1.00      0.81      3570

    accuracy                           0.68      5284
   macro avg       0.34      0.50      0.40      5284
weighted avg       0.46      0.68      0.54      5284

[[   0 1714]
 [   0 3570]]


/opt/oss/conda3/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/oss/conda3/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/oss/conda3/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


### Training

In [60]:
training_df = training_df.dropna()
training_df_2 = training_df_2.dropna()

X = training_df[training_df_2.columns]

y = training_df['dd_spayed_or_neutered']


oversample = RandomOverSampler(sampling_strategy=0.5, random_state=42)
X_over, y_over = oversample.fit_resample(X, y)
X_train, X_test, y_train, y_test = train_test_split(X_over, y_over, test_size=0.3, random_state=42)

clf = GaussianNB()
y_pred = clf.fit(X_train, y_train).predict(X_test)


print("Number of mislabeled points out of a total %d points : %d" % (X_test.shape[0], (y_test != y_pred).sum()))
print(metrics.classification_report(y_test, y_pred))
print(metrics.confusion_matrix(y_test, y_pred))

Number of mislabeled points out of a total 5217 points : 1745
              precision    recall  f1-score   support

       False       0.45      0.08      0.14      1715
        True       0.68      0.95      0.79      3502

    accuracy                           0.67      5217
   macro avg       0.57      0.52      0.47      5217
weighted avg       0.60      0.67      0.58      5217

[[ 143 1572]
 [ 173 3329]]


### Miscellaneous

In [61]:
miscellaneous_df = miscellaneous_df.dropna()
miscellaneous_df_2 = miscellaneous_df_2.dropna()

X = miscellaneous_df[miscellaneous_df_2.columns]

y = miscellaneous_df['dd_spayed_or_neutered']


oversample = RandomOverSampler(sampling_strategy=0.5, random_state=42)
X_over, y_over = oversample.fit_resample(X, y)
X_train, X_test, y_train, y_test = train_test_split(X_over, y_over, test_size=0.3, random_state=42)

clf = GaussianNB()
y_pred = clf.fit(X_train, y_train).predict(X_test)


print("Number of mislabeled points out of a total %d points : %d" % (X_test.shape[0], (y_test != y_pred).sum()))
print(metrics.classification_report(y_test, y_pred))
print(metrics.confusion_matrix(y_test, y_pred))

Number of mislabeled points out of a total 5037 points : 1200
              precision    recall  f1-score   support

       False       0.67      0.51      0.58      1623
        True       0.79      0.88      0.83      3414

    accuracy                           0.76      5037
   macro avg       0.73      0.70      0.71      5037
weighted avg       0.75      0.76      0.75      5037

[[ 835  788]
 [ 412 3002]]


After conducting SMOTE oversampling, in order to remedy the modeling issues previously faced due to the lack of respondents reporting that their dog is unneutered, precision and recall has improved across the board for the minority class('False). It would therefore be advisable that future researchers aiming to tackle this topic either attempt to acquire a larger set of survey responses to increase the diversity of their data, or utilize oversampling/undersampling techniques to potentially address any class imbalances.

# Model Construction: Decision Trees(Training and Prediction)

### Aggression

In [62]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report

In [63]:
X = aggression_df[aggression_df_2.columns]
y = aggression_df['dd_spayed_or_neutered']


oversample = RandomOverSampler(sampling_strategy=0.5, random_state=42)
X_over, y_over = oversample.fit_resample(X, y)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

clf = DecisionTreeClassifier(min_samples_leaf=30, random_state=42)
clf.fit(X_train, y_train)

pred_tree = clf.predict(X_test)

report = classification_report(pred_tree, y_test)
print(report)

              precision    recall  f1-score   support

       False       0.08      0.40      0.13        20
        True       1.00      0.97      0.98      3438

    accuracy                           0.97      3458
   macro avg       0.54      0.69      0.56      3458
weighted avg       0.99      0.97      0.98      3458



### Fear and Anxiety

In [64]:
X = fear_anxiety_df[fear_anxiety_df_2.columns]
y = fear_anxiety_df['dd_spayed_or_neutered']


oversample = RandomOverSampler(sampling_strategy=0.5, random_state=42)
X_over, y_over = oversample.fit_resample(X, y)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

clf = DecisionTreeClassifier(min_samples_leaf=30, random_state=42)
clf.fit(X_train, y_train)

pred_tree = clf.predict(X_test)

report = classification_report(pred_tree, y_test)
print(report)

              precision    recall  f1-score   support

       False       0.31      0.69      0.43        39
        True       1.00      0.98      0.99      3295

    accuracy                           0.98      3334
   macro avg       0.65      0.84      0.71      3334
weighted avg       0.99      0.98      0.98      3334



### Excitability

In [65]:
X = excitability_df[excitability_df_2.columns]
y = excitability_df['dd_spayed_or_neutered']


oversample = RandomOverSampler(sampling_strategy=0.5, random_state=42)
X_over, y_over = oversample.fit_resample(X, y)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

clf = DecisionTreeClassifier(min_samples_leaf=30, random_state=42)
clf.fit(X_train, y_train)

pred_tree = clf.predict(X_test)

report = classification_report(pred_tree, y_test)
print(report)

              precision    recall  f1-score   support

       False       0.00      0.00      0.00         0
        True       1.00      0.97      0.99      3624

    accuracy                           0.97      3624
   macro avg       0.50      0.49      0.49      3624
weighted avg       1.00      0.97      0.99      3624



/opt/oss/conda3/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/oss/conda3/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/oss/conda3/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


### Attachment

In [66]:
X = attachment_df[attachment_df_2.columns]
y = attachment_df['dd_spayed_or_neutered']


oversample = RandomOverSampler(sampling_strategy=0.5, random_state=42)
X_over, y_over = oversample.fit_resample(X, y)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

clf = DecisionTreeClassifier(min_samples_leaf=30, random_state=42)
clf.fit(X_train, y_train)

pred_tree = clf.predict(X_test)

report = classification_report(pred_tree, y_test)
print(report)

              precision    recall  f1-score   support

       False       0.00      0.00      0.00         0
        True       1.00      0.97      0.99      3625

    accuracy                           0.97      3625
   macro avg       0.50      0.49      0.49      3625
weighted avg       1.00      0.97      0.99      3625



/opt/oss/conda3/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/oss/conda3/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/oss/conda3/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


### Training

In [67]:
X = training_df[training_df_2.columns]
y = training_df['dd_spayed_or_neutered']


oversample = RandomOverSampler(sampling_strategy=0.5, random_state=42)
X_over, y_over = oversample.fit_resample(X, y)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

clf = DecisionTreeClassifier(min_samples_leaf=30, random_state=42)
clf.fit(X_train, y_train)

pred_tree = clf.predict(X_test)

report = classification_report(pred_tree, y_test)
print(report)

              precision    recall  f1-score   support

       False       0.00      0.00      0.00         0
        True       1.00      0.97      0.99      3581

    accuracy                           0.97      3581
   macro avg       0.50      0.49      0.49      3581
weighted avg       1.00      0.97      0.99      3581



/opt/oss/conda3/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/oss/conda3/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/oss/conda3/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


### Miscellaneous

In [68]:
X = miscellaneous_df[miscellaneous_df_2.columns]
y = miscellaneous_df['dd_spayed_or_neutered']


oversample = RandomOverSampler(sampling_strategy=0.5, random_state=42)
X_over, y_over = oversample.fit_resample(X, y)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

clf = DecisionTreeClassifier(min_samples_leaf=30, random_state=42)
clf.fit(X_train, y_train)

pred_tree = clf.predict(X_test)

report = classification_report(pred_tree, y_test)
print(report)

              precision    recall  f1-score   support

       False       0.34      0.65      0.45        57
        True       0.99      0.98      0.99      3402

    accuracy                           0.97      3459
   macro avg       0.67      0.81      0.72      3459
weighted avg       0.98      0.97      0.98      3459



In regards to the precision and recall scores for the minority class, the above decision tree models appear to be noticeably less performant than the Gaussian Naive Bayes models, even after oversampling the minority class. This may very likely be due to the fact that the dataset provided is not substantive enough to really warrant the usage of a more robust, intensive supervised learning approach such as decision trees.

# Model Construction: Random Forest(Training and Prediction)

In [69]:
from sklearn.ensemble import RandomForestClassifier

### Aggression

In [70]:
X = aggression_df[aggression_df_2.columns]
y = aggression_df['dd_spayed_or_neutered']


oversample = RandomOverSampler(sampling_strategy=0.5, random_state=42)
X_over, y_over = oversample.fit_resample(X, y)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

clf = RandomForestClassifier(max_depth=3, n_estimators=100, random_state=42)
clf.fit(X_train, y_train)

pred_forest = clf.predict(X_test)

report = classification_report(pred_forest, y_test)
print(report)

              precision    recall  f1-score   support

       False       0.01      1.00      0.02         1
        True       1.00      0.97      0.99      3457

    accuracy                           0.97      3458
   macro avg       0.50      0.99      0.50      3458
weighted avg       1.00      0.97      0.98      3458



### Fear and Anxiety

In [71]:
X = fear_anxiety_df[fear_anxiety_df_2.columns]
y = fear_anxiety_df['dd_spayed_or_neutered']


oversample = RandomOverSampler(sampling_strategy=0.5, random_state=42)
X_over, y_over = oversample.fit_resample(X, y)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

clf = RandomForestClassifier(max_depth=3, n_estimators=100, random_state=42)
clf.fit(X_train, y_train)

pred_forest = clf.predict(X_test)

report = classification_report(pred_forest, y_test)
print(report)

              precision    recall  f1-score   support

       False       0.00      0.00      0.00         0
        True       1.00      0.97      0.99      3334

    accuracy                           0.97      3334
   macro avg       0.50      0.49      0.49      3334
weighted avg       1.00      0.97      0.99      3334



/opt/oss/conda3/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/oss/conda3/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/oss/conda3/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


### Excitability

In [72]:
X = excitability_df[excitability_df_2.columns]
y = excitability_df['dd_spayed_or_neutered']


oversample = RandomOverSampler(sampling_strategy=0.5, random_state=42)
X_over, y_over = oversample.fit_resample(X, y)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

clf = RandomForestClassifier(max_depth=3, n_estimators=100, random_state=42)
clf.fit(X_train, y_train)

pred_forest = clf.predict(X_test)

report = classification_report(pred_forest, y_test)
print(report)

              precision    recall  f1-score   support

       False       0.00      0.00      0.00         0
        True       1.00      0.97      0.99      3624

    accuracy                           0.97      3624
   macro avg       0.50      0.49      0.49      3624
weighted avg       1.00      0.97      0.99      3624



/opt/oss/conda3/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/oss/conda3/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/oss/conda3/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


### Attachment

In [73]:
X = attachment_df[attachment_df_2.columns]
y = attachment_df['dd_spayed_or_neutered']


oversample = RandomOverSampler(sampling_strategy=0.5, random_state=42)
X_over, y_over = oversample.fit_resample(X, y)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

clf = RandomForestClassifier(max_depth=3, n_estimators=100, random_state=42)
clf.fit(X_train, y_train)

pred_forest = clf.predict(X_test)

report = classification_report(pred_forest, y_test)
print(report)

              precision    recall  f1-score   support

       False       0.00      0.00      0.00         0
        True       1.00      0.97      0.99      3625

    accuracy                           0.97      3625
   macro avg       0.50      0.49      0.49      3625
weighted avg       1.00      0.97      0.99      3625



/opt/oss/conda3/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/oss/conda3/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/oss/conda3/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


### Training

In [84]:
X = training_df[training_df_2.columns]
y = training_df['dd_spayed_or_neutered']


oversample = RandomOverSampler(sampling_strategy=0.5, random_state=42)
X_over, y_over = oversample.fit_resample(X, y)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

clf = RandomForestClassifier(max_depth=3, n_estimators=100, random_state=42)
clf.fit(X_train, y_train)

pred_forest = clf.predict(X_test)

report = classification_report(pred_forest, y_test)
print(report)


              precision    recall  f1-score   support

       False       0.00      0.00      0.00         0
        True       1.00      0.97      0.99      3581

    accuracy                           0.97      3581
   macro avg       0.50      0.49      0.49      3581
weighted avg       1.00      0.97      0.99      3581



/opt/oss/conda3/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/oss/conda3/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/oss/conda3/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


### Miscellaneous

In [75]:
X = miscellaneous_df[miscellaneous_df_2.columns]
y = miscellaneous_df['dd_spayed_or_neutered']


oversample = RandomOverSampler(sampling_strategy=0.5, random_state=42)
X_over, y_over = oversample.fit_resample(X, y)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

clf = RandomForestClassifier(max_depth=3, n_estimators=100, random_state=42)
clf.fit(X_train, y_train)

pred_forest = clf.predict(X_test)

report = classification_report(pred_forest, y_test)
print(report)

              precision    recall  f1-score   support

       False       0.00      0.00      0.00         0
        True       1.00      0.97      0.98      3459

    accuracy                           0.97      3459
   macro avg       0.50      0.48      0.49      3459
weighted avg       1.00      0.97      0.98      3459



/opt/oss/conda3/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/oss/conda3/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/oss/conda3/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Unlike the decision tree models in the preceding section, even after compensating for the class imbalance by oversampling the minority class, the random forest models above appear to only be predicting the majority signal(True). This suggests that the model is easily overfitting to the training data, a finding that is not entirely surprising given the small size of each dataframe. For future iterations of this analysis, should it be possible to acquire a dataset with more records, more complex ensemble learnig methods such as random forest may be more viable. For the purposes of our data, however, such complex models appear to produce problematic results.